// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBK0kPCxrIuSSknsQmtoMTvx3bXFv0Qd-0',
    appId: '1:246907453932:web:63d37ac160ccabc9e4c0c9',
    messagingSenderId: '246907453932',
    projectId: 'chat-flutter-3a61d',
    authDomain: 'chat-flutter-3a61d.firebaseapp.com',
    storageBucket: 'chat-flutter-3a61d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW0asGsYiR8toj9Mng7OyeF5bIV5WaBjM',
    appId: '1:246907453932:android:b62f72b79b5aedbbe4c0c9',
    messagingSenderId: '246907453932',
    projectId: 'chat-flutter-3a61d',
    storageBucket: 'chat-flutter-3a61d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9Pe2OJYbaFF2XdHRE-FT4QdQFr6prFFI',
    appId: '1:246907453932:ios:c2d07e740904554fe4c0c9',
    messagingSenderId: '246907453932',
    projectId: 'chat-flutter-3a61d',
    storageBucket: 'chat-flutter-3a61d.appspot.com',
    androidClientId: '246907453932-4loss4fo8jredj42avel4vpv4rvovjgf.apps.googleusercontent.com',
    iosClientId: '246907453932-o7ifu6eo7atgnehsl4g1qdvgtg9k8dhc.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9Pe2OJYbaFF2XdHRE-FT4QdQFr6prFFI',
    appId: '1:246907453932:ios:c2d07e740904554fe4c0c9',
    messagingSenderId: '246907453932',
    projectId: 'chat-flutter-3a61d',
    storageBucket: 'chat-flutter-3a61d.appspot.com',
    androidClientId: '246907453932-4loss4fo8jredj42avel4vpv4rvovjgf.apps.googleusercontent.com',
    iosClientId: '246907453932-o7ifu6eo7atgnehsl4g1qdvgtg9k8dhc.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );
}
